### ISSUE TITLE
It's not working on next^12.0.1

### ISSUE THREAD

**Issue by mecuong** [elado/next-with-less#14]
### Problem 
It's work find on next^11.x.x but error with next^12.0.1 
TypeError: Cannot read properties of undefined (reading 'oneOf')
    at Object.webpack (/Users/nguyencuong/Desktop/ShopME/node_modules/next-with-less/dist/index.js:61:15)

**Comment by handycode** [comment]
me too

**Comment by abreurapha** [comment]
same here

**Comment by handycode** [comment]
> fixed by updating to version `^2.0.2` :)

it works
