### ISSUE TITLE
Error in using with next 12.0.7

### ISSUE THREAD

**Issue by muhmushtaha** [elado/next-with-less#19]
TypeError: Cannot read property 'oneOf' of undefined

antd@3.26.20
next@12.0.7
next-with-less@2.0.2

**Comment by muhmushtaha** [comment]
This is my configs
![image](https://user-images.githubusercontent.com/25417060/144746494-fa0a366b-150a-4341-a173-d5a4ec0b3a9d.png)

**Comment by chemicalkosek** [comment]
https://github.com/elado/next-with-less/issues/18

**Comment by elado** [comment]
Thanks for reporting. Fixed in 2.0.4.

**Comment by tvervest** [comment]
Works like a charm again, thanks! 😄 🙏
