### ISSUE TITLE
Type error: Cannot find module '../../styles/dev.module.less' or its corresponding type declarations.

### ISSUE THREAD

**Issue by lofzefjg** [elado/next-with-less#27]
nextjs: 12.20.0
npm run dev ready
npm run build :
Type error: Cannot find module '../../styles/dev.module.less' or its corresponding type declarations.

**Comment by gregatgoogle** [comment]
You may need to declare less modules in type declarations: https://github.com/vercel/next.js/issues/9690#issuecomment-696662210.
