### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by Zeng95** [elado/next-with-less#30]
## Versions

- next: 13.0.0
- next-with-less: 2.0.5
- less-loader: 11.1.0
- less: 4.1.3
- antd: 4.24.4

## next.config.js
```js
const withLess = require("next-with-less");
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  lessLoaderOptions: {}
}

module.exports = withLess(nextConfig)
```

## Error Message
```js
TypeError: Cannot read properties of undefined (reading 'replace')
    at addLessToRegExp (/project/sandbox/node_modules/next-with-less/dist/index.js:21:31)
    at addLessToRuleTest (/project/sandbox/node_modules/next-with-less/dist/index.js:77:18)
    at /project/sandbox/node_modules/next-with-less/dist/index.js:87:23
    at Array.forEach (<anonymous>)
    at Object.webpack (/project/sandbox/node_modules/next-with-less/dist/index.js:81:21)
    at Object.getBaseWebpackConfig [as default] (/project/sandbox/node_modules/next/dist/build/webpack-config.js:1413:32)
    at async Promise.all (index 0)
    at async Span.traceAsyncFn (/project/sandbox/node_modules/next/dist/trace/trace.js:79:20)
    at async Span.traceAsyncFn (/project/sandbox/node_modules/next/dist/trace/trace.js:79:20)
    at async HotReloader.start (/project/sandbox/node_modules/next/dist/server/dev/hot-reloader.js:332:30)
```

![image](https://user-images.githubusercontent.com/12603244/205004291-80e92e0f-40e4-476f-8570-8800f9329538.png)

## Examples
[nextjs-demo](https://codesandbox.io/p/sandbox/compassionate-mountain-h63t3w?workspace=%257B%2522activeFileId%2522%253Anull%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clb4tk0yv03jd3b6joukzey3w%2522%253A%257B%2522key%2522%253A%2522clb4tk0yv03jd3b6joukzey3w%2522%252C%2522name%2522%253A%2522Default%2520Space%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522clb4tk0yv03je3b6jg5r24td6%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clb4tk0yv03jd3b6joukzey3w%2522%257D)

**Comment by Zeng95** [comment]
The error message shows up after installing [@next/font](https://nextjs.org/blog/next-13#nextfont)

**Comment by mayrsascha** [comment]
Having the same issue, makes @next/font unusable unfortunately... I really regret using LESS with Next.js at this point

**Comment by Zeng95** [comment]
> Having the same issue, makes @next/font unusable unfortunately... I really regret using LESS with Next.js at this point

What's the reason for you to choose less? :)

**Comment by mayrsascha** [comment]
I chose Ant Design as my component library, which generally works and looks good with my application, but only supports Less

**Comment by chemicalkosek** [comment]
> I chose Ant Design as my component library, which generally works and looks good with my application, but only supports Less

AntD since 5.0 doesn't use less. You can use this guide to migrate: https://ant.design/docs/react/migration-v5
